# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171023_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Disciplina')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
                ('professor', models.CharField(max_length=50, verbose_name='Professor da Disciplina')),
                ('descricao', models.TextField(blank=True, verbose_name='Comentários sobre a Disciplina')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
